spring:
  application:
    name: backend-bd
  datasource:
    url: jdbc:mysql://localhost:3306/client_product
    username: root
    password: M1x_2021
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8080