spring:
  application:
    name: backend-bd
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/client_product}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:CHANGE_ME}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE